backend:
  name: github
  repo: ani-ferreira/project
  branch: main

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    slug: "{{slug}}"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: project
    label: Project
    folder: project
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
